theme: jekyll-theme-midnight

# Site Settings
title: [Spencer Pride]
description: [Mr. Pride's Portfolio (Work In Progress)]
url: "https://sparklyspencer.github.io/"

# User Settings
username: SparklySpencer
user_description: Their Royal Majesty, Lord Rainbowness, Prince Sparkles
user_title: Creative Director of SoulSongCycle
email: theos.kengen@gmail.com
github_username: SparklySpencer
gplus_username: SparklySpencer
